apiVersion: v1
kind: Pod
metadata:
  name: port-forward-pod
  namespace: mlflow
  annotations:
    # I'm not fixing these, this whole pod is a modification of https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rds-external-access.html
    # with securityContext added
    checkov.io/skip1: CKV_K8S_43=This isn't a debugging tool
    checkov.io/skip2: CKV_K8S_10=This isn't a debugging tool
    checkov.io/skip3: CKV_K8S_14=This isn't a debugging tool
    checkov.io/skip4: CKV_K8S_12=This isn't a debugging tool
    checkov.io/skip5: CKV_K8S_8=This isn't a debugging tool
    checkov.io/skip6: CKV_K8S_13=This isn't a debugging tool
    checkov.io/skip7: CKV_K8S_40=This isn't a debugging tool
    checkov.io/skip8: CKV_K8S_22=This isn't a debugging tool
    checkov.io/skip9: CKV_K8S_35=This isn't a debugging tool
    checkov.io/skip10: CKV_K8S_38=This isn't a debugging tool
    checkov.io/skip11: CKV_K8S_11=This isn't a debugging tool
    checkov.io/skip12: CKV_K8S_9=This isn't a debugging tool
    checkov.io/skip13: CKV2_K8S_6=This isn't a debugging tool
spec:
  containers:
  - name: port-forward-pod
    image: docker.io/ministryofjustice/port-forward
    ports:
    - containerPort: 5432
    env:
    - name: REMOTE_HOST
      valueFrom:
        secretKeyRef:
          name: mlflow-auth-rds
          key: address
    - name: LOCAL_PORT
      value: "5432"
    - name: REMOTE_PORT
      valueFrom:
        secretKeyRef:
          name: mlflow-auth-rds
          key: port
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
