---
apiVersion: v1
kind: Pod
metadata:
  name: airflow-kubernetes-smoke-test
  namespace: airflow
  annotations:
    # These Chekov checks are skipped because they are not relevant to this pod, its used for smoke testing by the platform team
    checkov.io/skip1: CKV_K8S_43
    checkov.io/skip2: CKV_K8S_9
    checkov.io/skip3: CKV_K8S_31
    checkov.io/skip4: CKV_K8S_15
    checkov.io/skip5: CKV_K8S_8
    checkov.io/skip6: CKV_K8S_30
    checkov.io/skip7: CKV_K8S_37
    checkov.io/skip8: CKV_K8S_40
    checkov.io/skip9: CKV_K8S_20
    checkov.io/skip10: CKV_K8S_28
    checkov.io/skip11: CKV_K8S_22
    checkov.io/skip12: CKV_K8S_38
    checkov.io/skip13: CKV2_K8S_6
spec:
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool
                operator: In
                values:
                  - general-spot
  tolerations:
    - key: compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool
      operator: Equal
      value: general-spot
      effect: NoSchedule
  restartPolicy: Never
  containers:
    - name: main
      image: ghcr.io/ministryofjustice/analytical-platform-airflow-python-base:1.4.0
      command: ["/bin/sh", "-c", "date && cat /etc/os-release && sleep 120"]
      resources:
        requests:
          memory: 64Mi
          cpu: 100m
        limits:
          memory: 128Mi
          cpu: 200m
      
