---
name: terraform strategy

on:
  workflow_call:
    inputs:
      application:
        type: string
        required: true
        description: "Application name for which this strategy matrix pipeline should run."
    outputs:
      matrix:
        description: "Matrix JSON string to feed that can be used as strategy in a separate terraform job"
        value: ${{ jobs.strategy.outputs.matrix }}

jobs:
  strategy:
    name: "strategy"
    runs-on: ubuntu-latest
    outputs:
      matrix: "${{ steps.strategy.outputs.matrix }}"
    steps:
      - name: Check out Repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4

      - name: Generate Strategy Matrix
        id: strategy
        run: |
          set -euo pipefail

          # Fetch the main branch so we can compare against it.
          git fetch origin main

          # Determine the commit to use as the tip of the branch.
          # For pull request events (ref starts with "refs/pull/"), use the PR's head commit.
          if [[ "${GITHUB_REF}" == refs/pull/* ]]; then
            head_commit=$(jq --raw-output .pull_request.head.sha "$GITHUB_EVENT_PATH")
          else
            head_commit=HEAD
          fi

          # 1) Fetch environment data from <application>.json.
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            # On a branch: production gets "plan", dev/test get "plan_apply".
            curl -s -X GET "https://raw.githubusercontent.com/ministryofjustice/modernisation-platform/main/environments/${{ inputs.application }}.json" \
              | jq -c '.environments[] as $env |
                  if $env.name | contains("production") then
                    {"target": $env.name, "action": "plan"}
                  else
                    {"target": $env.name, "action": "plan_apply"}
                  end' \
              > envlist.json
          else
            # On main: all accounts get "plan_apply".
            curl -s -X GET "https://raw.githubusercontent.com/ministryofjustice/modernisation-platform/main/environments/${{ inputs.application }}.json" \
              | jq -c '.environments[] | {"target": .name, "action": "plan_apply"}' \
              > envlist.json
          fi

          # 2) Discover valid subfolders that contain a platform_backend.tf file.
          # We always include the application folder itself as "root".
          COMPONENTS="root"
          if [ -d "terraform/environments/${{ inputs.application }}" ]; then
            for d in $(find "terraform/environments/${{ inputs.application }}" -mindepth 1 -maxdepth 1 -type d); do
              subfolder="$(basename "$d" | tr -d '\r\n')"
              if [ -f "$d/platform_backend.tf" ]; then
                [ "$subfolder" = ".terraform" ] && continue
                COMPONENTS="$COMPONENTS $subfolder"
              fi
            done
          fi

          echo "Discovered components (folders with platform_backend.tf): $COMPONENTS"

          # 3) Build the final matrix by looping over environments and components.
          #    Only add an entry if the folder has changes relative to main.
          #    For "root", we only consider changes to files directly in the application folder.
          echo "[" > final-list.json
          firstEntry=true

          while IFS= read -r envobj; do
            for comp in $COMPONENTS; do
              if [ "$comp" = "root" ]; then
                # For the top-level (application) folder, restrict to files directly within it.
                folder="terraform/environments/${{ inputs.application }}"
                if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
                  merge_base=$(git merge-base origin/main "$head_commit")
                  changed_files=$(git diff --name-only "$merge_base" "$head_commit" -- "$folder")
                else
                  changed_files=$(git diff --name-only HEAD~1 HEAD -- "$folder")
                fi
                top_level_changed=false
                prefix="$folder/"
                for f in $changed_files; do
                  # Only consider files directly under $folder (i.e. with no further subdirectories)
                  if [[ "$f" == "$prefix"* ]]; then
                    rel="${f#$prefix}"
                    if [[ "$rel" != *"/"* ]]; then
                      top_level_changed=true
                      break
                    fi
                  fi
                done
                if ! $top_level_changed; then
                  echo "Skipping 'root' as no top-level changes detected in '$folder'"
                  continue
                fi
              else
                # For component subfolders, use the standard diff check.
                folder="terraform/environments/${{ inputs.application }}/$comp"
                if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
                  merge_base=$(git merge-base origin/main "$head_commit")
                  if git diff --quiet "$merge_base" "$head_commit" -- "$folder"; then
                    echo "Skipping '$comp' as no changes detected in '$folder' (branch compared to merge base)"
                    continue
                  fi
                else
                  if git diff --quiet HEAD~1 HEAD -- "$folder"; then
                    echo "Skipping '$comp' as no changes detected in '$folder' (main branch)"
                    continue
                  fi
                fi
              fi

              # If changes are detected, add an entry to the matrix.
              if [ "$firstEntry" = true ]; then
                firstEntry=false
              else
                echo "," >> final-list.json
              fi
              echo -n "$envobj" | jq --arg comp "$comp" '. + {"component": $comp}' >> final-list.json
            done
          done < envlist.json || true

          echo "]" >> final-list.json

          # Wrap the JSON array in {"include": [...] } for the GitHub Actions matrix.
          echo -n '{"include":' > matrix.out
          cat final-list.json >> matrix.out
          echo '}' >> matrix.out

          matrix=$(cat matrix.out | jq -r)
          echo "Matrix is:"
          echo "$matrix"

          # Output the matrix for subsequent jobs.
          echo 'matrix<<EOF' >> $GITHUB_OUTPUT
          echo "${matrix}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
